name: Deploy on Push Event
on: push # This workflow will run on push events
jobs:
  test: # this is taken from the test.yml to have more jobs in the same workflow but testing as first job and deploy as second job.
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy: # this is the new job for deployment
    runs-on: ubuntu-latest
    # needs: test # this job needs the test job to be completed before starting this job.
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build the project for deployment
        run: npm run build
      - name: Deploy the project
        run: echo "Deploying the project" # this is a placeholder for the actual deployment command.